spring.application.name=Scm2.0

# Server
 server.port=${PORT:8080}


# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Database
 spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/scm20}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
 spring.datasource.password=${DB_PASSWORD}



# Google OAuth
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.scope=profile,email
 spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
 spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}



# GitHub OAuth
spring.security.oauth2.client.registration.github.client-name=GitHub
spring.security.oauth2.client.registration.github.scope=profile,email
 spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
 spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}



# Cloudinary
 cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
 cloudinary.api-key=${CLOUDINARY_API_KEY}
 cloudinary.api-secret=${CLOUDINARY_API_SECRET}

